// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ItMvJZvhx6FICsez5tHlyy9JfY_LSBU',
    appId: '1:626803379016:web:b1c0fefea4494898fa017d',
    messagingSenderId: '626803379016',
    projectId: 'hedieaty-be01f',
    authDomain: 'hedieaty-be01f.firebaseapp.com',
    storageBucket: 'hedieaty-be01f.firebasestorage.app',
    measurementId: 'G-NRZNKNFW22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwvu7GjlJTReHvrZZYmcoTKxDoG3-L3M',
    appId: '1:626803379016:android:bebeec5f057c884efa017d',
    messagingSenderId: '626803379016',
    projectId: 'hedieaty-be01f',
    storageBucket: 'hedieaty-be01f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPc-lm0pj-ondC-DLr-7NZz13Aeb-TLWk',
    appId: '1:626803379016:ios:1ea58981984eb108fa017d',
    messagingSenderId: '626803379016',
    projectId: 'hedieaty-be01f',
    storageBucket: 'hedieaty-be01f.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );
}
